spring:
  application:
    name: discovery
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: SpringCloudZadanie
      #fail-fast: true
  profiles:
    active: development
